add DataRangeWidget to define DataGrid to show
quantum-entangled/machine-learning-ui pull request #43
Opened 2022-11-29 11:44 UTC by AlexTcots

add DataRangeWidget to define row_begin,row_end, columns_begin and columns_end for DataGrid

2022-12-04 15:11 UTC, quantum-entangled requested changes
Sorry for taking to long, I've reviewed your PR and commented several things. In general, this functionality shouldn't be implemented separately from existing DataGrid widget, so please remake this a little bit and also note several app architecture changes from recent commits.

2022-12-04 15:11 UTC, quantum-entangled commented on src/main.ipynb
> +   ],
`*.ipynb` metadata changes are "junk" changes for VCS, I'm working on automatic pre-comit tool for clearing all outputs and execution counts, but for now you should do it manually and not add them to commits.

2022-12-04 16:51 UTC, AlexTcots commented on src/Managers/DataManager.py
> +                                 self._range[3]))
OK, I will remake it.

2022-12-15 13:40 UTC, AlexTcots commented
yes, please review the new commits

2022-12-15 13:46 UTC, quantum-entangled commented
Ok, I will do it soon. If you'll be ready for a review next time you change some code, please, assign me as a reviewer first time or re-request review in this section, cause otherwise I won't receive any notifications.
![image](https://user-images.githubusercontent.com/86056534/207874864-f2c5fbcb-8854-4573-b293-eac81ab6026b.png)

2022-12-15 13:47 UTC, AlexTcots commented
Ok, I got it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Ivan ***@***.***>
Sent: Thursday, December 15, 2022 4:46 PM
To: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Subject: Re: [quantum-entangled/machine-learning-ui] add DataRangeWidget to define DataGrid to show (PR #43)


Ok, I will do it soon. If you'll be ready for a review next time you change some code, please, assign me as a reviewer first time or re-request review in this section, cause otherwise I won't receive any notifications.
[image]<https://user-images.githubusercontent.com/86056534/207874864-f2c5fbcb-8854-4573-b293-eac81ab6026b.png>

—
Reply to this email directly, view it on GitHub<https://github.com/quantum-entangled/machine-learning-ui/pull/43#issuecomment-1353100755>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/APXDWMYYEZXYGUQJXHZMIGTWNMOMBANCNFSM6AAAAAASOMHLXU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-12-16 14:10 UTC, quantum-entangled requested changes
I reviewed your changes, some things should be simplified still. Please, check them out and ask any questions, if you have some.

2022-12-16 14:10 UTC, quantum-entangled commented on src/Managers/DataManager.py
> +                       begin_c: Protocol, end_c: Protocol) -> None:
I'm not sure why do you use `Protocol`s here? I assume these values are just `int`s.

2022-12-16 14:10 UTC, quantum-entangled commented on src/UI/CustomWidgets/DataPreparation/DataGridWidget.py
> +                                         )
Using ranges of columns and rows as parameters for `show_data_grid()`, you won't need this function at all.

2022-12-16 14:10 UTC, quantum-entangled commented on src/Managers/DataManager.py
> +                                 self._range[3]))
I think we don't really need to print ranges here, because they will be shown on sliders anyway.

2022-12-19 20:25 UTC, merged

2022-12-19 20:26 UTC, quantum-entangled commented
Good job, closing it.